<?xml version="1.0"?>
<robot name="body" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <link name="body_link">
        <visual name="visual">
            <geometry>
            <box size="${body['length']} ${body['width']} ${body['height']}"/>
            </geometry>
        </visual>

        <collision name="collision">
            <geometry>
            <box size="${body['length']} ${body['width']} ${body['height']}"/>
            </geometry>
        </collision>
    </link>

    <joint name="body_joint" type="fixed">
        <parent link="base_link" />
        <child link="body_link" />
        <origin xyz="${body['length']/2} 0 0" />
    </joint>


    <!-- Wheel links -->

    <link name="back_left_wheel_link">
    </link>
    <joint name="back_left_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="0 ${body['width']/2 + wheel['length']/2} 0" rpy="-${M_PI_2} 0 0"/>
    </joint>

    <link name="back_right_wheel_link">
    </link>
    <joint name="back_right_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="0 -${body['width']/2 + wheel['length']/2} 0" rpy="${M_PI_2} 0 0"/>
    </joint>

    <!-- Caster link -->

    <link name="base_to_caster_link">
    </link>
    <joint name="base_to_caster_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_to_caster_link" />
        <origin xyz="0.35 0 -${caster['radius']}" rpy="0 0 0"/>
    </joint>

</robot>