  type: "diff_drive_controller/DiffDriveController"
  publish_rate: 50

  left_wheel: ['left_wheel_joint']
  right_wheel: ['right_wheel_joint']
  wheel_separation: 0.25
  wheel_radius: 0.1
  
  # Odometry covariances for the encoder output of the robot. These values should
  # be tuned to your robot's sample odometry data, but these values are a good place
  # to start
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Top level frame (link) of the robot description
  base_frame_id: base_link

  # Velocity and acceleration limits for the robot
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           : 0.08   # m/s
      has_acceleration_limits: false
      max_acceleration       : 0.08   # m/s^2
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : 0.05  # rad/s
      has_acceleration_limits: false
      max_acceleration       : 0.05   # rad/s^2
